services:
  app:
    build:
      context: ..
      dockerfile: container/Dockerfile
    container_name: kiwi-app
    environment:
      PORT: "3000"
    ports:
      - "8080:80"
    restart: "no"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: kiwi-cloudflared
    depends_on:
      - app
    command: tunnel --no-autoupdate --protocol http2 --loglevel info --url http://app:80
    restart: "no"
